# Perfil "dev": Postgres corriendo en tu propia máquina (localhost)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camelracing_db
    username: postgres
    password: juanjose1414
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # actualiza las tablas automáticamente mientras se realiza el desarrollo
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: "una-clave-secreta-larga-de-al-menos-32-caracteres-para-firmar-tokens"
  expiration-ms: 3600000   # 1 hora, en milisegundos